#!/bin/bash
#
# Copy from stdin to GUI copy-paste buffer
#
# Author: Kyle Manna -> http://blog.kylemanna.com
# License: MIT -> http://opensource.org/licenses/MIT
#

# Check if invoked from an fssh session
if [ -n "$LC_FSSH_PORT" -a -n "$LC_FSSH_USER" -a -n "$LC_FSSH_COPY" ]; then
	# Connect to the remote host and issue copy command
	ssh \
		-o "StrictHostKeyChecking=no" \
		-o "VisualHostKey=no" \
		-p $LC_FSSH_PORT \
		-l $LC_FSSH_USER \
		localhost \
		PATH=$LC_FSSH_PATH $LC_FSSH_COPY
else
	# Assume issued locally, no ssh
	if [ "$(uname)" = "Darwin" ]; then
	   reattach-to-user-namespace pbcopy
	else
	   xclip -i
	fi
fi
