#!/bin/bash
#
# Copy from stdin to GUI copy-paste buffer
#
# Author: Kyle Manna -> http://blog.kylemanna.com
# License: MIT -> http://opensource.org/licenses/MIT
#

# Check if invoked from an rssh session
if [ -n "$LC_RSSH_PORT" -a -n "$LC_RSSH_USER" -a -n "$LC_RSSH_COPY" ]; then
	# Connect to the remote host and issue copy command
	ssh \
		-o "StrictHostKeyChecking=no" \
		-p $LC_RSSH_PORT \
		-l $LC_RSSH_USER \
		localhost \
		$LC_RSSH_COPY
else
	# Assume issued locally, no ssh
	if [ "$(uname)" = "Darwin" ]; then
	   reattach-to-user-namespace pbcopy
	else
	   xclip -i
	fi
fi
