#!/usr/bin/env python
#
# Paste from GUI copy-paste buffer to stdout
#
# Author: Kyle Manna -> http://blog.kylemanna.com
# License: MIT -> http://opensource.org/licenses/MIT
#

import os
import subprocess
import sys

if __name__ == '__main__':

   # Check if invoked from an fssh session
   if ('LC_FSSH_PORT' in os.environ
        and 'LC_FSSH_USER' in os.environ
        and 'LC_FSSH_PASTE' in os.environ):

      # Connect to the remote host and issue copy command
      argv = ['ssh',
              os.environ.get('LC_FSSH_PASTE_ARGS', ''),
              '-o', 'VisualHostKey=no',
              '-p', os.environ['LC_FSSH_PORT'],
              '-l', os.environ['LC_FSSH_USER'],
              'localhost',
              'PATH={0}'.format(os.environ.get('LC_FSSH_PATH', '')),
              '{0}'.format(os.environ['LC_FSSH_PASTE']) ]

      #print "argv = {}".format(argv)

      p = subprocess.Popen(argv, stdout=subprocess.PIPE)

      result = p.communicate()

      sys.stdout.write(result[0])

   else:
      # Assume issued locally, no ssh
      if sys.platform.startswith('darwin'):
         subprocess.call(['reattach-to-user-namespace', 'pbpaste'])
      else:
         subprocess.call(['xclip', '-o'])
